#!/bin/bash
NAME=$(basename $1)
DEFAULT='~/Repos/Cockpit\ 3'

if [[ "$1" = /* ]]; then
    TARGET=$1
else
    TARGET="'$DEFAULT/$1'"
fi

tmux-sync.sh $NAME "start_microfrontend_server '$TARGET'" "start_microfrontend_client '$TARGET'"
